In [1]:
# Import libraries
import pandas as pd
import mysql.connector

In [ ]:
db = mysql.connector.connect(
                host = 'localhost',
                user = 'root',
                password = 'your passward',
                database = 'database'
)
cur = db.cursor()

In [3]:


# Now run your query
tables = 'show tables'
cur.execute(tables)
results = cur.fetchall()
print(results)

[('categories',), ('customers',), ('employees',), ('order_details',), ('orders',), ('products',), ('shippers',), ('suppliers',)]

In [4]:
# Now run your query
tables = 'show tables'
cur.execute(tables)
results = cur.fetchone()
print(results)

('categories',)

In [8]:
query = '''select * from customers'''
cur.execute(query)
customers = cur.fetchall()

#create dataframe
df = pd.DataFrame(customers)
df

,0,1,2,3,4,5,6
0,1,Alfreds Futterkiste,Maria Anders,Obere Str. 57,Berlin,12209,Germany
1,2,Ana Trujillo Emparedados y helados,Ana Trujillo,Avda. de la Constitución 2222,México D.F.,05021,Mexico
2,3,Antonio Moreno Taquería,Antonio Moreno,Mataderos 2312,México D.F.,05023,Mexico
3,4,Around the Horn,Thomas Hardy,120 Hanover Sq.,London,WA1 1DP,UK
4,5,Berglunds snabbköp,Christina Berglund,Berguvsvägen 8,Luleå,S-958 22,Sweden
...,...,...,...,...,...,...,...
86,87,Wartian Herkku,Pirkko Koskitalo,Torikatu 38,Oulu,90110,Finland
87,88,Wellington Importadora,Paula Parente,"Rua do Mercado, 12",Resende,08737-363,Brazil
88,89,White Clover Markets,Karl Jablonski,305 - 14th Ave. S. Suite 3B,Seattle,98128,USA
89,90,Wilman Kala,Matti Karttunen,Keskuskatu 45,Helsinki,21240,Finland
90,91,Wolski,Zbyszek,ul. Filtrowa 68,Walla,01-012,Poland

# 1. select customers names together with each order by the customer

In [9]:

query = '''select c.CustomerName, o.OrderID
from customers as c
join orders as o
using (CustomerID)'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['Name', 'order_id'])
df

                                   Name  order_id
0    Ana Trujillo Emparedados y helados     10308
1               Antonio Moreno Taquería     10365
2                       Around the Horn     10355
3                       Around the Horn     10383
4                    Berglunds snabbköp     10278
..                                  ...       ...
191              Wellington Importadora     10420
192                White Clover Markets     10269
193                White Clover Markets     10344
194                         Wilman Kala     10248
195                              Wolski     10374

[196 rows x 2 columns]

# 2. select orderID together with name of the employee who handled the order

In [10]:
query = '''select o.OrderID , e.FirstName, e.LastName
from Orders as o
join employees as e
using (EmployeeID);'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['order_id', 'first_name', 'last_name'])
df

     order_id first_name  last_name
0       10258      Nancy    Davolio
1       10270      Nancy    Davolio
2       10275      Nancy    Davolio
3       10285      Nancy    Davolio
4       10292      Nancy    Davolio
..        ...        ...        ...
191     10263       Anne  Dodsworth
192     10324       Anne  Dodsworth
193     10331       Anne  Dodsworth
194     10386       Anne  Dodsworth
195     10411       Anne  Dodsworth

[196 rows x 3 columns]

# 3. select customers who did not placed any order yet

In [11]:
query = '''select c.CustomerID, c.CustomerName
from customers as c
left join orders as o
using (CustomerID)
where o.CustomerID is null'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['customer_id', 'customer_name'])
df

    customer_id                         customer_name
0             1                   Alfreds Futterkiste
1             6               Blauer See Delikatessen
2            12            Cactus Comidas para llevar
3            22  FISSA Fabrica Inter. Salchichas S.A.
4            26                   France restauration
5            32               Great Lakes Food Market
6            40                  La corne d'abondance
7            42         Laughing Bacchus Wine Cellars
8            43                  Lazy K Kountry Store
9            45                     Let's Stop N Shop
10           50                          Maison Dewey
11           53                           North/South
12           57                     Paris spécialités
13           64                         Rancho grande
14           74                  Spécialités du monde
15           78                       The Cracker Box
16           82     Trail's Head Gourmet Provisioners

In [12]:
query = '''select OrderID, ProductName
from order_details as od
join products as p
using (ProductID)'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['order_id', 'product_name'])
df

     order_id                     product_name
0       10285                            Chais
1       10294                            Chais
2       10317                            Chais
3       10348                            Chais
4       10354                            Chais
..        ...                              ...
513     10366  Original Frankfurter grüne Soße
514     10367  Original Frankfurter grüne Soße
515     10399  Original Frankfurter grüne Soße
516     10417  Original Frankfurter grüne Soße
517     10421  Original Frankfurter grüne Soße

[518 rows x 2 columns]

# 6. Select customer together with the products that he bought

In [13]:
query = '''select c.CustomerID, c.CustomerName, p.ProductName, od.OrderID
from customers as c
join orders using (CustomerID)
join order_details as od using (OrderID)
join products as p using (ProductID)
order by c.CustomerID asc'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['customer_id', 'customer_name', 'product_name', 'order_id'])
df

,customer_id,customer_name,product_name,order_id
0,2,Ana Trujillo Emparedados y helados,Gudbrandsdalsost,10308
1,2,Ana Trujillo Emparedados y helados,Outback Lager,10308
2,3,Antonio Moreno Taquería,Queso Cabrales,10365
3,4,Around the Horn,Guaraná Fantástica,10355
4,4,Around the Horn,Ravioli Angelo,10355
...,...,...,...,...
513,90,Wilman Kala,Queso Cabrales,10248
514,90,Wilman Kala,Singaporean Hokkien Fried Mee,10248
515,90,Wilman Kala,Mozzarella di Giovanni,10248
516,91,Wolski,Gorgonzola Telino,10374
517,91,Wolski,Escargots de Bourgogne,10374

# 7. Select product names together with the name of corresponding category

In [15]:
query = '''select p.ProductID, p.ProductName, c.CategoryName
from products as p
join categories as c
using (CategoryID)
order by p.ProductID asc'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['product_id', 'product_name', 'category_name'])
df

    product_id                     product_name category_name
0            1                            Chais     Beverages
1            2                            Chang     Beverages
2            3                    Aniseed Syrup    Condiments
3            4     Chef Anton's Cajun Seasoning    Condiments
4            5           Chef Anton's Gumbo Mix    Condiments
..         ...                              ...           ...
72          73                       Röd Kaviar       Seafood
73          74                    Longlife Tofu       Produce
74          75             Rhönbräu Klosterbier     Beverages
75          76                     Lakkalikööri     Beverages
76          77  Original Frankfurter grüne Soße    Condiments

[77 rows x 3 columns]

# 8. Select orders together with the name of the shipping company

In [16]:
query = '''select o.OrderID, o.CustomerID, o.EmployeeID,o.OrderDate, s.ShipperName
from orders as o
join shippers as s 
using (ShipperID)
order by o.OrderID'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['order_id', 'customer_id', 'Employee_id', 'order_date', 'shipper_name'])
df

     order_id  customer_id  Employee_id  order_date      shipper_name
0       10248           90            5  1996-07-04  Federal Shipping
1       10249           81            6  1996-07-05    Speedy Express
2       10250           34            4  1996-07-08    United Package
3       10251           84            3  1996-07-08    Speedy Express
4       10252           76            4  1996-07-09    United Package
..        ...          ...          ...         ...               ...
191     10439           51            6  1997-02-07  Federal Shipping
192     10440           71            4  1997-02-10    United Package
193     10441           55            3  1997-02-10    United Package
194     10442           20            3  1997-02-11    United Package
195     10443           66            8  1997-02-12    Speedy Express

[196 rows x 5 columns]

# 9. Select customers with id greater than 50 together with each order they made

In [18]:
query = '''select c.CustomerID, c.CustomerName, o.OrderID
from customers as c
join orders as o
using (CustomerID)
where c.CustomerID > 50'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['customer_id', 'customer_name', 'order_id'])
df

    customer_id           customer_name  order_id
0            51          Mère Paillarde     10332
1            51          Mère Paillarde     10339
2            51          Mère Paillarde     10376
3            51          Mère Paillarde     10424
4            51          Mère Paillarde     10439
..          ...                     ...       ...
94           88  Wellington Importadora     10420
95           89    White Clover Markets     10269
96           89    White Clover Markets     10344
97           90             Wilman Kala     10248
98           91                  Wolski     10374

[99 rows x 3 columns]

# 10. Select employees together with orders with order id greater than 10400

In [22]:
query = '''select o.OrderID, e.EmployeeID, e.FirstName, e.LastName
from orders as o
join employees as e
using(EmployeeID)
where o.OrderID > 10400
order by e.EmployeeID'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['order_id', 'employee_id', 'first_name', 'last_name'])
df

    order_id  employee_id first_name  last_name
0      10405            1      Nancy    Davolio
1      10401            1      Nancy    Davolio
2      10422            2     Andrew     Fuller
3      10407            2     Andrew     Fuller
4      10404            2     Andrew     Fuller
5      10414            2     Andrew     Fuller
6      10420            3      Janet  Leverling
7      10429            3      Janet  Leverling
8      10442            3      Janet  Leverling
9      10441            3      Janet  Leverling
10     10409            3      Janet  Leverling
11     10410            3      Janet  Leverling
12     10433            3      Janet  Leverling
13     10413            3      Janet  Leverling
14     10415            3      Janet  Leverling
15     10438            3      Janet  Leverling
16     10434            3      Janet  Leverling
17     10432            3      Janet  Leverling
18     10436            3      Janet  Leverling
19     10418            4   Margaret    Peacock
20     10419            4   Margaret    Peacock
21     10417            4   Margaret    Peacock
22     10426            4   Margaret    Peacock
23     10427            4   Margaret    Peacock
24     10440            4   Margaret    Peacock
25     10403            4   Margaret    Peacock
26     10430            4   Margaret    Peacock
27     10431            4   Margaret    Peacock
28     10423            6    Michael     Suyama
29     10439            6    Michael     Suyama
30     10425            6    Michael     Suyama
31     10424            7     Robert       King
32     10428            7     Robert       King
33     10406            7     Robert       King
34     10402            8      Laura   Callahan
35     10435            8      Laura   Callahan
36     10421            8      Laura   Callahan
37     10437            8      Laura   Callahan
38     10416            8      Laura   Callahan
39     10412            8      Laura   Callahan
40     10408            8      Laura   Callahan
41     10443            8      Laura   Callahan
42     10411            9       Anne  Dodsworth

# 11. Select the most expensive product

In [24]:
query = '''select ProductID, ProductName, Price
from products
order by price desc
limit 1'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['product_id', 'product_name', 'price'])
df

   product_id   product_name  price
0          38  Côte de Blaye  263.5

# 12. Select the second most expensive product

In [25]:
query = '''select ProductID, ProductName, Price
from products
order by price desc
limit 1 offset 1'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['product_id', 'product_name', 'price'])
df

   product_id             product_name   price
0          29  Thüringer Rostbratwurst  123.79

# 13. Select name and price of each product, sort the result by price in decreasing order

In [29]:
query = '''select ProductName, Price
from products
order by price desc'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['product_name', 'price'])
df

               product_name   price
0             Côte de Blaye  263.50
1   Thüringer Rostbratwurst  123.79
2           Mishi Kobe Niku   97.00
3    Sir Rodney's Marmalade   81.00
4          Carnarvon Tigers   62.50
..                      ...     ...
72                Tourtière    7.45
73                 Filo Mix    7.00
74                    Konbu    6.00
75       Guaraná Fantástica    4.50
76                  Geitost    2.50

[77 rows x 2 columns]

# 14. Select 5 most expensive products

In [30]:
query = '''select ProductID, ProductName, Price
from products
order by price desc
limit 5'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['product_id', 'product_name', 'price'])
df

   product_id             product_name   price
0          38            Côte de Blaye  263.50
1          29  Thüringer Rostbratwurst  123.79
2           9          Mishi Kobe Niku   97.00
3          20   Sir Rodney's Marmalade   81.00
4          18         Carnarvon Tigers   62.50

# 15. Select 5 most expensive products without the most expensive (in final 4 products)

In [33]:
query = '''select ProductID, ProductName, Price
from products
order by price desc
limit 4 offset 1'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['product_id', 'product_name', 'price'])
df

   product_id             product_name   price
0          29  Thüringer Rostbratwurst  123.79
1           9          Mishi Kobe Niku   97.00
2          20   Sir Rodney's Marmalade   81.00
3          18         Carnarvon Tigers   62.50

# 16. Select name of the cheapest product (only name) without using LIMIT and OFFSET

In [35]:
query = '''select ProductName, Price
from products
where Price = (select min(Price) from products)'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['product_name', 'price'])
df

  product_name  price
0      Geitost    2.5

# 17. Select name of the cheapest product (only name) using subquery

In [37]:
query = '''select ProductName
from products
where Price = (select min(Price) from products)'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = [ 'product_name'])
df

  product_name
0      Geitost

# 18. Select number of employees with LastName that starts with 'D'

In [42]:
query = '''select employeeID, FirstName, LastName
from employees
where LastName like 'D%'
'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['employee_id', 'first_name', 'last_name'])
df

   employee_id first_name  last_name
0            1      Nancy    Davolio
1            9       Anne  Dodsworth

# 19. Select orderID together with the total price of  that Order, order the result by total price of order in increasing order

In [43]:
query = '''select od.OrderID, sum(od.Quantity * p.Price) as total_price
from order_details as od
join products as p 
using (ProductID)
group by od.OrderID
order by total_price asc
'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['order_id', 'total_price'])
df

     order_id  total_price
0       10271        60.00
1       10422        62.46
2       10391       108.00
3       10281       108.20
4       10308       111.00
..        ...          ...
191     10360      9244.25
192     10353     13427.00
193     10417     14104.00
194     10424     14366.50
195     10372     15353.60

[196 rows x 2 columns]

# 20. Select customer who spend the most money

In [44]:
query = '''select c.CustomerID, c.CustomerName, sum(od.Quantity * p.Price) as total_price
from customers as c
join orders as o using (CustomerID)
join order_details as od using (OrderID)
join products as p using (ProductID)
group by c.CustomerID
order by total_price desc
'''

cur.execute(query)
data = cur.fetchall()

df = pd.DataFrame(data, columns = ['customer_id', 'customer_name','total_price'])
df

    customer_id                       customer_name  total_price
0            20                        Ernst Handel     35631.21
1            51                      Mère Paillarde     23362.60
2            71                  Save-a-lot Markets     22500.06
3            65          Rattlesnake Canyon Grocery     18421.42
4            63                          QUICK-Stop     18178.80
..          ...                                 ...          ...
69           54              Océano Atlántico Ltda.       399.00
70           18                     Du monde entier       336.00
71           13          Centro comercial Moctezuma       126.00
72            2  Ana Trujillo Emparedados y helados       111.00
73           27                      Franchi S.p.A.        62.46

[74 rows x 3 columns]